// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.BoolMultiBindingAndConditionConverter.ConvertBack(System.Object,System.Type[],System.Object,System.Globalization.CultureInfo)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.BoolMultiBindingOrConditionConverter.ConvertBack(System.Object,System.Type[],System.Object,System.Globalization.CultureInfo)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.CollectionCountOrArrayLengthConverter.ConvertBack(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.Converters.StringEqualsConverter.ConvertBack(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.DoubleAbsoluteValueConverter.ConvertBack(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.DoubleMaxValueMultiBindingConverter.ConvertBack(System.Object,System.Type[],System.Object,System.Globalization.CultureInfo)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.DoubleMinValueMultiBindingConverter.ConvertBack(System.Object,System.Type[],System.Object,System.Globalization.CultureInfo)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.DoubleValuesMultiplyMultiBindingConverter.ConvertBack(System.Object,System.Type[],System.Object,System.Globalization.CultureInfo)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.DoubleValuesSumMultiBindingConverter.ConvertBack(System.Object,System.Type[],System.Object,System.Globalization.CultureInfo)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.GetTypeConverter.ConvertBack(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.RegexIsMatchConverter.ConvertBack(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.RegexIsMatchMultiBindingConverter.ConvertBack(System.Object,System.Type[],System.Object,System.Globalization.CultureInfo)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.RegexMatchValueConverter.ConvertBack(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.RegexMatchValueMultiBindingConverter.ConvertBack(System.Object,System.Type[],System.Object,System.Globalization.CultureInfo)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.RegexReplaceConverter.ConvertBack(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.RegexReplaceMultiBindingConverter.ConvertBack(System.Object,System.Type[],System.Object,System.Globalization.CultureInfo)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.StringContainsConverter.ConvertBack(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.StringContainsMultiBindingConverter.ConvertBack(System.Object,System.Type[],System.Object,System.Globalization.CultureInfo)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.StringFormatConverter.ConvertBack(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)~System.Object")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.StringFormatMultiBindingConverter.ConvertBack(System.Object,System.Type[],System.Object,System.Globalization.CultureInfo)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.StringReplaceMultiBindingConverter.ConvertBack(System.Object,System.Type[],System.Object,System.Globalization.CultureInfo)~System.Object[]")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("General", "RCS1079:Throwing of new NotImplementedException.", Justification = "<Pending>", Scope = "member", Target = "~M:CodingSeb.Converters.TypeCheckingConverter.ConvertBack(System.Object,System.Type,System.Object,System.Globalization.CultureInfo)~System.Object")]
